server:
  port: 8082
spring:
  application:
    name: "CrediYa_Reports"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    active: dev
aws:
  region: "us-east-2"
