server:
  port: 8082
spring:
  application:
    name: "CrediYa_Reports"
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    active: "dev"
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: "my-super-secret-key-change-me-123456"
aws:
  region: "us-east-2"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
entrypoint:
  sqs:
    region: "us-east-2"
    endpoint: "http://localhost:4566"
    queueUrl: "https://sqs.us-east-2.amazonaws.com/557649279192/CrediYa_Totals"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
